version: '3.7'
services: 
    nodejs:
        build:
            context: ./docker/nodejs
            dockerfile: Dockerfile
        container_name: xtasks-node
        tty: true
        volumes:
            - ./src:/home/node/app
            - ./yarn-init.sh:/home/node/app/yarn-init.sh
        ports:
            - ${APP_PORT}:8080
        networks:
            - express-tasks
        depends_on:
            - postgres
        
    postgres:
        build:
            context: ./docker/postgres
            dockerfile: Dockerfile
        container_name: xtasks-postgres
        restart: always
        environment:
            - POSTGRES_USER=${DB_POSTGRES_USER}
            - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
            - POSTGRES_DB=${DB_POSTGRES_DB_NAME}
        volumes:
            - ./docker/postgres/tmp-postgres:/var/lib/postgresql/data
            - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d
        ports:
            - 5433:5432
        networks:
            - express-tasks

    prism:
        build:
            context: ./docker/prism
            dockerfile: Dockerfile
        container_name: xtasks-prism
        restart: always
        volumes:
            - ./xtasks-openapi.yaml:/openapi.yaml
        ports:
            - 4010:4010
        networks:
            - express-tasks 

    swagger_ui:
        image: swaggerapi/swagger-ui
        container_name: xtasks-swaggerui
        environment:
            - URL=http://localhost:3003/xtasks-openapi.yaml
        volumes:
            - ../xtasks-openapi.yaml:/usr/share/nginx/html/xtasks-openapi.yaml
        ports:
            - 3003:8080
        networks:
            - express-tasks
networks:
    express-tasks:
# volumes:
#    postgres-db:
#        driver_opts:
#            type: none
#            device: ./tmp-postgres
#            o: bind
